# Numpy

- práce s vícerozměrnými poli (tenzory)
- efektivní operace implementované v C
- interface k operacím lineární algebry
- další funkce ...

[referenční dokumentace](https://docs.scipy.org/doc/numpy-1.13.0/reference/index.html)

Další zdroje:
- [Stanford lecture](https://web.stanford.edu/~schmit/cme193/lec/lec5.pdf)

- [100 cvičení z Numpy](http://yvesguidet.no-ip.biz/complementsMureaux/100_numpy_exercises.pdf)

- [Python and SciPy lecture notes](https://hal.inria.fr/hal-01206546/file/ScipyLectures-simple.pdf)

Dále předpokládáme import knihovny ve tvaru:


In [2]:
import numpy as np

## Array
- reprezentace N rozměrného tenzoru
- mnohé operace (řezání, transpozice) provádí jen změnu přístupu ke stále stejným datů

In [3]:
# Konverze ze standarnich Pythnonich typu.
list_matrix =[ list(range(3)), list(range(1,4))]
print("List matrix:", list_matrix)
a = np.array(list_matrix)
print("Numpy matrix:\n", a, '\npython type:', type(a))


List matrix: [[0, 1, 2], [1, 2, 3]]
Numpy matrix:
 [[0 1 2]
 [1 2 3]] 
python type: <class 'numpy.ndarray'>


### Array - atributy

    a.ndim,  a.shape,  a.size,  a.dtype
   

In [4]:
# Počet dimenzí/os/axis pole
print("ndim", a.ndim)

# Rozměry pole v jednotlivých osách.
print("shape", a.shape)

# Počet prvků pole.
print("size", a.size)

# Type prvků pole (všechny prvky mají stejný typ).
print("dtype", a.dtype)


ndim 2
shape (2, 3)
size 6
dtype int64


Matice `a` má prvky typu `int64`. Numpy automaticky zvolí `int` pokud jsou všechny zadané prvky `int`. Explicitně je možno požadovat jiný typ pomocí parametru `dtype`:

In [5]:
from sys import getsizeof

print("float type:\n", np.array(list_matrix, dtype=float))
print("complex type:\n", np.array(list_matrix, dtype=complex))
print("bool type:\n", np.array(list_matrix, dtype=bool))

# Type variants with different memory footprint.
a8 = np.array(list_matrix, dtype="int8")
print("\nint8 type:\n", a8)
print("element type: ", a8.dtype)

print("a int 64 memory size:", getsizeof(a),)
print("a int 8 memory size:", getsizeof(a8))


float type:
 [[0. 1. 2.]
 [1. 2. 3.]]
complex type:
 [[0.+0.j 1.+0.j 2.+0.j]
 [1.+0.j 2.+0.j 3.+0.j]]
bool type:
 [[False  True  True]
 [ True  True  True]]

int8 type:
 [[0 1 2]
 [1 2 3]]
element type:  int8
a int 64 memory size: 160
a int 8 memory size: 118


### Inicializace array

In [ ]:
# sekvence: počátek, konec, krok
print("arange: ", np.arange(1.1, 10, 2.1))

# sekvence: počátek, konec, počet bodů
print("linspace: ", np.linspace(1.1, 10, 4))

# zeros, ones, eye, full
print("zeros :\n", np.zeros((2,4)))
print("ones :\n", np.ones((2,4)))
print("full :\n", np.full((2,4), 3.14))

# jednotkova matice
print("eye :\n", np.eye(4))

Další funkce pro tvorbu polí viz:

[Numpy doc: array creation routines](https://docs.scipy.org/doc/numpy/reference/routines.array-creation.html)

Pro čtení polí (matic) z textových tabulek lze použít funkci 
[`loadtxt`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.loadtxt.html#numpy.loadtxt).
Nicméně tato funkce je notoricky VELMI pomalá (stále pomalá v roce 2018, verze Numpy 1.16) a nevhodná pro 
soubory přesahující 10 tisíc řádek. Nejrychlejší funkce na čtení textových tabulek (CSV soubory) je funce z knihovny Pandas (viz. další přednášky).


### Přetížené operátory
Binární operátory je možné provádět pro dvě pole se stejným `shape`.

In [7]:
a = np.array([[0,1,2], [1,2,3]])
b = np.ones((2,3))

In [8]:
a + b

array([[1., 2., 3.],
       [2., 3., 4.]])

In [9]:
a * b

array([[0., 1., 2.],
       [1., 2., 3.]])

In [10]:
a > b


array([[False, False,  True],
       [False,  True,  True]])

In [ ]:
# I funkce lze aplikovat po jednotlivých elementech:
np.sin(np.pi * a / 2)

### Array indexing and slicing
Podpora více indexů najednou v hranatých závorkách pro indexování vícerozměrných polí.

Řez ve formě `[start : end : step]` vybere v jedné dimenzi pouze indexy začínající `start`, s krokem `step` a menší než `end`.

In [ ]:
# Více indexů povoleno
print(a)
a[0,1]

In [ ]:
# Pomocí řezů lze vybírat pod výběry.
# první sloupec
a[:, 0]

In [ ]:
# Druhý řádek, prvky 0..2
a[1, 0:2]

In [ ]:
# Poslední dva prvky druhého řádku
a[1, -3:-1]

In [ ]:
# První řádek pozpátku.
a[0,::-1]

In [ ]:
a[0, ...]

In [ ]:
# Konverze vektoru na matici, přidání axis
b=a[0]
print(b)
print(b[None, :])
print(b[:, None])

### Broadcasting
Pokud operandy nemají stejný tvar, je možno operaci provést pokud lze jeden operand rozšířit na shape druhého operandu:
1. Operand s nižším `ndim` se zleva doplní dimenzemi s rozměrem 1 do počtu dimenzí druhého operandu.
2. Pokud v některé dimenzi je rozměr jednoho operandu N a rozměr druhého 1. Druhý operand se v této ose použije N krát.

Obecná pravidla konverze polí menší dimenze na pole vyšší dimenze při (binárních) operacích:

[Numpy broadcasting](https://docs.scipy.org/doc/numpy-1.13.0/reference/ufuncs.html#broadcasting)

In [ ]:
# Nejjednodušší příklad, násobení skalárem
b = 2 * a
b

In [ ]:
# ... je ekvivalentní násobení maticí dvojek.
two = np.full((2,3), 2.0)
two * a

In [12]:
# Broadcasting pro vektor a matici.
a = np.arange(4).reshape((2,2))
print("a matrix:\n", a)
b = np.arange(3,5)
print("b vector:\n", b)
b+a

a matrix:
 [[0 1]
 [2 3]]
b vector:
 [3 4]


array([[3, 5],
       [5, 7]])

Explicitní broadcasting pomocí `None` indexu. Mnohem lepší srozumitelnost.

In [14]:
a = np.arange(4)
# outer product
a[None, :] * a[:, None] 

array([[0, 0, 0, 0],
       [0, 1, 2, 3],
       [0, 2, 4, 6],
       [0, 3, 6, 9]])

### Array reshaping

In [ ]:
# Rozbalení dat do prostého pole, může být vnitřně realizováno jen pomocí metadat.
# ... vrátí se "view".
b = a.ravel()
print(b)
b[0] =10
a

In [ ]:
# Stejné dělá metoda flatten, ale nyní vrací kopii skutčeně rozbalených dat. 
b = a.flatten()
print(b)
b[0] = 100
a

In [ ]:
# Změna tvaru pomocí přiřazení do attributu shape:
b.shape = (3, 2)
b

In [ ]:
# transpozice
a.T
a.transpose()

In [ ]:
# Obecná transpozice jak permutace axis.

# Třírozměrný tenzor, osy si označíme pomocí prvků 1,2,3 
xyz  = np.zeros( (2,2,2) )
xyz[0,0,0] = 111
xyz[1,0,0] = 1
xyz[0,1,0] = 2
xyz[0,0,1] = 3

print("\nxyz: \n", xyz)
# Prohodíme první a druhou osu:
print("\ntranspose: \n", xyz.transpose((1,0,2)))

## Operace s více poli.


### Array stacking
Posazení dvou matic (polí) nad sebe, vedle sebe ... 

In [ ]:
a= list_matrix =np.array([ list(range(3)), list(range(1,4))])
print(a)
b = a[0]
print(b)

In [ ]:
# Více polí stejného shape na pole vyšší dimenze. 
# Např. z vektorů udělat matici (vektory jako sloupce)
np.stack((a[0], a[1], b), axis=1)

In [ ]:
# To samé v řádcích
np.stack((a[0], a[1], b), axis=0)

In [ ]:
# Více polí různý shape, zachování dimenze. Stejný shape kolmo na axise slučování.
np.concatenate((a, b[None,:]), axis=0) # V axis 1 stejný shape. 

## Basic operations
Get help and try functions:
- min(), max(), maximum(), minimum()
- average(), mean()
- diff()
- dot()
- sum(), prod(), cumsum(), cumprod()

### Linear algebra

In [ ]:
from numpy import la


## Klíčové funkce

Numpy:
- np.dot()
- np.inner(), np.outer(), np.kron()
- la.norm()
- la.solve(), la.lu(), la.cholesky(), la.qr()
- la.eig(), la.svd()

np.fft module

In [ ]:
# Vzniklá vnějším/tenzorovým součinem dvou vektorů.
xy = np.outer(np.arange(1,3,1), np.arange(1,4,2))
# Zápis stejného pomocí maticového součinu:

print("xy: \n", xy)

print("\nshapes: \n", xy[:,:,None].shape, np.arange(1,5,3)[None,:].shape)
xyz = np.dot(xy[:,:,None], np.arange(1,5,3)[None,:])


In [ ]:
c = [[1, 12], [3,4],[1,4]]
nc = np.array(c)
nc
nc[1]

In [ ]:
np.minimum(nc[0, 1:], nc[1,])

In [ ]:
np.zeros((0,2))


# Cvičení

1. Nastudujte a vyzkoušejte si základní funkce z modulu np.random:
   
   random, rand, seed, choice
   
2. Vygenerujte:
   
   - náhodnou matici A, shape (3, 3)
   - náhodný vektor b, shape (3, )
   
3. vyřešte soustavu $Ax=b$ a ověřte řešení pomocí výpočtu $Ax - b$

4. Vygenerujte pole dvojic náhodných bodů (úseček) v jednotkovém čtverci, jako matici (N, 2, 2)

5. Vypočtěte pole délek úseček (jednořádkový  kód).

6. Vytvořte pole X, Y, Z, kde X obsahuje x souřednice prvních bodů, Y je y souřadnice prvních bodů, z je logaritmus délek úseček.

7. Vypočtěte průmernou délku úseček a směrodatnou odchylku.

8. Náročnější úkol, působení hmotných bodů: 
    
   1. Vygenerujte náhodné pole bodů v jednotkové krychli a pole náhodných hmotností těchto bodů (libovolně).
   2. Napište funkci, která pro zadaný index $i$. Vypočte sílu kterou na hmotný bod $X_i$ působí ostatní hmotné body:
      
      $$ F_i = \sum_{j\ne i} G \frac{m_i m_j}{|R_{ij}|^3} R_{ij},\quad R_{ij}  =  X_i - X_j$$


In [ ]:
L=la.norm( mat[:,1,:] - mat[:,0,:], axis=1)
X = mat[:, 0, 0]
Z = np.log(L)